# Generated by Django 2.0.5 on 2019-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('midfielder', 'Mid_off'), ('wicketKeeper', 'Wicket_Keeper'), ('gullypoint', 'Gully_point'), ('midfielder', 'Mid_on'), ('long', 'Long_on'), ('none', 'None'), ('bowler', 'Bowler'), ('allrounder', 'All_rounder'), ('slip', 'Slip'), ('batsman', 'Batsman'), ('long', 'Long_off')], default='none', max_length=20),
        ),
    ]
