# Generated by Django 2.0.5 on 2019-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0004_auto_20190421_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('bowler', 'Bowler'), ('batsman', 'Batsman'), ('midfielder', 'Mid_on'), ('midfielder', 'Mid_off'), ('long', 'Long_on'), ('slip', 'Slip'), ('allrounder', 'All_rounder'), ('none', 'None'), ('wicketKeeper', 'Wicket_Keeper'), ('gullypoint', 'Gully_point'), ('long', 'Long_off')], default='none', max_length=20),
        ),
    ]
