# Generated by Django 2.0.5 on 2019-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0007_auto_20190421_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('bowler', 'Bowler'), ('gullypoint', 'Gully_point'), ('none', 'None'), ('long', 'Long_off'), ('allrounder', 'All_rounder'), ('long', 'Long_on'), ('slip', 'Slip'), ('midfielder', 'Mid_off'), ('batsman', 'Batsman'), ('wicketKeeper', 'Wicket_Keeper'), ('midfielder', 'Mid_on')], default='none', max_length=20),
        ),
    ]
