# Generated by Django 2.0.5 on 2019-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0008_auto_20190421_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('bowler', 'Bowler'), ('gullypoint', 'Gully_point'), ('midfielder', 'Mid_on'), ('long', 'Long_off'), ('batsman', 'Batsman'), ('allrounder', 'All_rounder'), ('slip', 'Slip'), ('wicketKeeper', 'Wicket_Keeper'), ('midfielder', 'Mid_off'), ('none', 'None'), ('long', 'Long_on')], default='none', max_length=20),
        ),
    ]
