# Generated by Django 2.0.5 on 2019-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0009_auto_20190421_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_minute',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('allrounder', 'All_rounder'), ('long', 'Long_off'), ('long', 'Long_on'), ('batsman', 'Batsman'), ('wicketKeeper', 'Wicket_Keeper'), ('gullypoint', 'Gully_point'), ('none', 'None'), ('slip', 'Slip'), ('midfielder', 'Mid_off'), ('bowler', 'Bowler'), ('midfielder', 'Mid_on')], default='none', max_length=20),
        ),
    ]
