# Generated by Django 2.0.5 on 2019-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0010_auto_20190421_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('long', 'Long_on'), ('midfielder', 'Mid_off'), ('none', 'None'), ('gullypoint', 'Gully_point'), ('slip', 'Slip'), ('midfielder', 'Mid_on'), ('wicketKeeper', 'Wicket_Keeper'), ('allrounder', 'All_rounder'), ('bowler', 'Bowler'), ('long', 'Long_off'), ('batsman', 'Batsman')], default='none', max_length=20),
        ),
    ]
