# Generated by Django 2.0.5 on 2019-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0014_auto_20190421_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('long', 'Long_on'), ('allrounder', 'All_rounder'), ('midfielder', 'Mid_on'), ('slip', 'Slip'), ('gullypoint', 'Gully_point'), ('bowler', 'Bowler'), ('none', 'None'), ('batsman', 'Batsman'), ('wicketKeeper', 'Wicket_Keeper'), ('midfielder', 'Mid_off'), ('long', 'Long_off')], default='none', max_length=20),
        ),
    ]
