# Generated by Django 2.0.5 on 2019-04-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0015_auto_20190421_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('allrounder', 'All_rounder'), ('none', 'None'), ('gullypoint', 'Gully_point'), ('wicketKeeper', 'Wicket_Keeper'), ('bowler', 'Bowler'), ('long', 'Long_on'), ('long', 'Long_off'), ('midfielder', 'Mid_on'), ('slip', 'Slip'), ('batsman', 'Batsman'), ('midfielder', 'Mid_off')], default='none', max_length=20),
        ),
    ]
