# Generated by Django 2.0.5 on 2019-04-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0016_auto_20190421_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='squad_position',
            field=models.CharField(choices=[('long', 'Long_on'), ('midfielder', 'Mid_on'), ('bowler', 'Bowler'), ('gullypoint', 'Gully_point'), ('none', 'None'), ('allrounder', 'All_rounder'), ('wicketKeeper', 'Wicket_Keeper'), ('long', 'Long_off'), ('batsman', 'Batsman'), ('midfielder', 'Mid_off'), ('slip', 'Slip')], default='none', max_length=20),
        ),
    ]
